### ISSUE TITLE
resetFragments重置的时候

### ISSUE THREAD

**Issue by AndMy** [Aspsine/FragmentNavigator#10]
resetFragments重置的时候我有个问题想请教
被重置的Bfragment，里面有成员变量int b，
   重置前成员变量 b = 2；
   重置后成员变量b = 2；
重置后成员变量为什么不是初始化状态？

**Comment by Aspsine** [comment]
```java
FragmentNavigator#resetFragments(int position)
```
方法会先remove所有position的fragment。然后重新调用
```java
FragmentNavigatorAdapter#onCreateFragment(int position)
```
来初始化指定位置的fragment，add到视图中。

检查一下
```java
FragmentNavigatorAdapter#onCreateFragment(int position)
```
这个方法中是否复用了fragment的实例。

**Comment by AndMy** [comment]
好的，谢谢了 
@Override
    public void onDestroyView() {
        sHandler.removeCallbacks(mRunnable);
        tvText = null;
        progressBar = null;
        super.onDestroyView();
    }
tvText = null;progressBar = null;这个是避免引用异常？

**Comment by Aspsine** [comment]
对于fragment这类含生命周期组件，我们所有的代码都在生命周期方法里。一般很少有引用异常发生。
Fragment#onDestroyView() 顾名思义就是销毁view的方法。
view 销毁了，如果fragment 还被引用，view 就不能真正被回收。置为null可以提早帮助回收。
