### ISSUE TITLE
这个和 fragmentTabhost 有什么区别？

### ISSUE THREAD

**Issue by slyang520** [Aspsine/FragmentNavigator#2]
这个和 fragmentTabhost 有什么区别？

**Comment by Aspsine** [comment]
首先说明，我在demo中采用类似于FragmentTabHost的布局是因为这种布局方式是最常见的，大家也最熟悉。FragmentNavigator并不局限于这种布局。

相同点：
1. FragmentNavigator和FragmentTabHost都有在同一个Layout中的切换Fragment的功能。

不同点：
1. FragmentNavigator是纯粹的Fragment Controller，而FragmentTabHost 是一个ViewGroup。
2. FragmentNavigator使用起来更加灵活，能适应各种布局需要。FragmentTabHost只能固定使用一种布局。
3. 同样在类似FragmentTabHost的布局下。FragmentNavigator对tabView的样式类型是没有要求的，而FragmentTabHost只能和TabWidget配合使用。
4. FragmentNavigator对Fragment的切换是调用showFragment(...)来完成的，而FragmentTabHost点击TabWidget设置监听后，会自动切换Fragment。没办法阻止页面的切换。比如有这样一个需求，点击第三个Tab在为未登陆状态下不需要切换Tab，跳向登陆页。FragmentTabHost是不能完成这种需求的。
5. FragmentTabHost中对Fragment的切换是采用add，onAttach, onDetach这种方式。FragmentNavigator采用add，show，hide的方式。
6. FragmentNavigator支持remove操作，支持刷新fragment的操作。
7. FragmentTabHost在各个版本的v4包中实现略有出入，且封装方式有点反人类，用的人并不多。
暂时列举这么多。具体在api使用方面二者差异很大。就不详细列举了。
