### ISSUE TITLE
How do you handle onBackPressed for Child Fragments?

### ISSUE THREAD

**Issue by amanzan** [Aspsine/FragmentNavigator#6]
I cloned the repo and added a button in contacts fragment to add a child fragment inside. My purpose was trying to test what happened when back button was tapped. Instead of popping out the newly created child fragment, and display the "parent" contacts fragment, tapping back just closes the app.

Is there any way to handle this situation?

**Comment by Aspsine** [comment]
You need to handle onBackPressed yourself.

This lib only take care of the top level fragments.
