### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by dazeGitHub** [Aspsine/FragmentNavigator#9]
和demo用的方式一样，但是有时候bugly 上边就报这个异常:

#8309 java.lang.IllegalStateException
Fragment already added: FragmentYiFan{1db2378e #4 id=0x7f0900cd 1MainActivity}

android.support.v4.app.FragmentManagerImpl.addFragment(Unknown Source)

**Comment by Aspsine** [comment]
@dazeGitHub 可以贴一下详细堆栈么？

**Comment by dazeGitHub** [comment]
1 android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1916)
--
2 android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:765)
3 android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
4 android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
5 android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
6 android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
7 android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
8 android.os.Handler.handleCallback(Handler.java:739)
9 android.os.Handler.dispatchMessage(Handler.java:95)
10 android.os.Looper.loop(Looper.java:179)
11 android.app.ActivityThread.main(ActivityThread.java:5769)
12 java.lang.reflect.Method.invoke(Native Method)
13 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
14 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

**Comment by dazeGitHub** [comment]
哦，我知道了，那个 adapter 中的 TAGS  传的不对，现在好了，可以关闭 issue 了

**Comment by alfredzhang0728** [comment]
@dazeGitHub 这个问题 版本升级到1.0.4 就修复了是吧？ 我现在的版本是1.0.2 有这个问题
